apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: registry.gitlab.com/your-group/python-k8-app:latest
          command: ["alembic", "upgrade", "head"]
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/app.db
      volumes:
        - name: sqlite-storage
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4